Categorias - Wesley
andre-digitalcollege/DigitalStore pull request #1
Opened 2022-12-04 00:54 UTC by wesley-azevedo

Finalizado o "categorias".

2022-12-10 19:02 UTC, allanhal approved these changes

2022-12-10 19:09 UTC, allanhal commented on src/components/Categorias.module.css
> +.cardDestaque {
Recomendo colocar o CSS para cada componente.

2022-12-10 19:11 UTC, andre-digitalcollege commented on src/components/Categorias.module.css
> +.cardDestaque {
que leitura

2022-12-10 19:15 UTC, allanhal approved these changes

2022-12-10 19:24 UTC, allanhal commented on src/components/Categorias.module.css
> +    border-style: none;
`cursor: pointer;`

2022-12-10 19:25 UTC, allanhal requested changes
Comentários

2022-12-10 19:32 UTC, merged

2023-01-01 20:51 UTC, andre-digitalcollege commented on src/components/Categorias.module.css
> +.cardDestaque {
ao mover deu erro, vscode nao atualizou os enderecos, porque nao sei mas vou tentar novamente